settings:
  callback_base: "http://ikpk.notnull.cc:6789"
  timezone: "Asia/Shanghai"
  data_dir: "./data/sqlite"
  app_secret: "notnull_callback_secret_2024"
#  ingress_aliases:
#    event_type: [ "reporting_type", "etype", "type" ]
#    ad_id: [ "ca_id", "aid", "adid" ]
#    click_id: [ "clickid", "clid", "clickId" ]
#    ua: [ "user_agent", "ua" ]
#    device_os: [ "os" ]
#    device_model: [ "model" ]
#    device_android_id: [ "androidId", "android_id", "androidid" ]
#    device_mac: [ "mac", "device_mac" ]
#    callback: [ "callback_url", "callback" ]

# NotNull广告平台上游配置（公共接口，无需验证）
upstreams:
  - id: "adapi"
    name: "微风互动"
    description: ""
    adapters:
      outbound:
        click:
          method: "GET"
          url: "http://ad.adapi.cn/click?aid={{aid}}&did={{did}}&os={{os}}&ts={{ts}}&callback={{callback}}&oaid={{oaid}}&imei={{imei}}&android_id={{android_id}}&idfa={{idfa}}&caid={{caid}}&ip={{ip}}&ua={{ua}}&model={{model}}&x={{x}}"
          macros:
            # 必填参数
            aid: "udm.ad.ad_id | url_encode()"
            did: "const:kpk"
            os: "udm.device.os | to_upper()"
            ts: "udm.time.ts"
            callback: "cb_url() | url_encode()"
            # Android
            oaid: "udm.device.oaid | url_encode()"
            imei: "udm.device.imei | url_encode()"
            android_id: "udm.device.android_id | url_encode()"
            # iOS
            idfa: "udm.device.idfa | url_encode()"
            caid: "udm.device.caid | url_encode()"
            # 可选
            ip: "udm.net.ip | url_encode()"
            ua: "udm.net.ua | normalize_encode()"
            model: "udm.device.model | url_encode()"
            x: "udm.meta.ext.custom_id | url_encode()"
          timeout_ms: 3000
          retry: {max: 2, backoff_ms: 500}
      # NotNull平台回调处理配置（无验证）
      inbound_callback:
        event:
          source: "query"  # 回调参数来源于URL查询参数
          field_map:
            "udm.event.type": "const:event"                    # 固定为event类型
            "udm.event.name": "query.event_type"                  # 事件类型：ACTIVATED/REGISTERED/PAID/RETAINED
            "udm.meta.amount": "query.amount"                # 付费金额（仅付费事件）
            "udm.meta.days": "query.days"                    # 留存天数（仅留存事件）
            "udm.time.ts": "now_ms()"                         # 使用当前时间戳


  - id: "duokaiyou"
    name: "ad-68a58f8ab82a4-向僵尸开炮"
    description: "ad-68a58f8ab82a4-向僵尸开炮"
    adapters:
      outbound:
        click:
          method: "GET"
          url: "http://adsense-api.duokaiyou.com/v1/monitor/mr?ca_id={{ad_id}}&imei={{imei}}&imei_md5={{imei_md5}}&androidid={{androidid}}&androidid_md5={{androidid_md5}}&oaid={{oaid}}&oaid_md5={{oaid_md5}}&clickid={{click_id}}&ip={{ip}}&os={{os}}&model={{model}}&brand={{brand}}&os_version={{os_version}}&mac={{mac}}&ts={{ts}}&user_agent={{user_agent}}&callback_url={{callback}}&reporting_type={{reporting_type}}"
          macros:
            ad_id: "udm.ad.ad_id | url_encode()"
            imei: "udm.device.imei | url_encode()"
            imei_md5: "udm.device.imei | hash_md5() | to_upper()"
            androidid: "udm.device.android_id | url_encode()"
            androidid_md5: "udm.device.android_id | hash_md5() | to_upper()"
            oaid: "udm.device.oaid | url_encode()"
            oaid_md5: "udm.device.oaid | hash_md5() | to_upper()"
            click_id: "uuid_v4()"
            ip: "udm.net.ip | url_encode()"
            os: "udm.device.os | to_lower()"
            model: "udm.device.model | url_encode()"
            brand: "udm.device.brand | url_encode()"
            os_version: "udm.device.os_version | floor()"
            mac: "udm.device.mac | url_encode()"
            ts: "udm.time.ts"
            user_agent: "udm.net.ua | normalize_encode()"
            callback: "cb_url() | replace('__EVENT__','__EVENT_TYPE__') | url_encode()"
            reporting_type: "udm.event.type"
          timeout_ms: 3000
          retry: { max: 2, backoff_ms: 500 }
#      配置回调
      inbound_callback:
        event:
          source: "query"  # 回调参数来源于URL查询参数
          field_map:
            "udm.event.type": "const:event"                    # 固定为event类型
            "udm.event.name": "query.event_type"              # 事件类型：activated/reg/pay                     # 使用当前时间戳

# 路由配置
routes:
  - match_key: "ad_id"
    rules:
      - equals: "10_60_683572_8"
        upstream: "adapi"
      - equals: "68a58f8ab82a4"
        upstream: "duokaiyou"
