settings:
  callback_base: "https://cbkpk.notnull.cc"
  timezone: "Asia/Shanghai"
  data_dir: "./data/sqlite"
  app_secret: "notnull_callback_secret_2024"

# NotNull广告平台上游配置（公共接口，无需验证）
upstreams:
  - id: "adapi"
    name: "微风互动"
    description: ""
    adapters:
      outbound:
        click: &click_tpl
          method: "GET"
          url: "http://ad.adapi.cn/click?aid={{aid}}&did={{did}}&os={{os}}&ts={{ts}}&callback={{callback}}&oaid={{oaid}}&imei={{imei}}&android_id={{android_id}}&idfa={{idfa}}&caid={{caid}}&ip={{ip}}&ua={{ua}}&model={{model}}&x={{x}}"
          macros:
            # 必填参数
            aid: "udm.ad.campaign_id | url_encode()"
            did: "const:kpk"
            os: "udm.device.os | to_upper()"
            ts: "udm.time.ts"
            callback: "cb_url() | url_encode()"
            # Android
            oaid: "udm.device.oaid | url_encode()"
            imei: "udm.device.imei | url_encode()"
            android_id: "udm.device.android_id | url_encode()"
            # iOS
            idfa: "udm.device.idfa | url_encode()"
            caid: "udm.device.caid | url_encode()"
            # 可选
            ip: "udm.net.ip | url_encode()"
            ua: "udm.net.ua | url_encode()"
            model: "udm.device.model | url_encode()"
            x: "udm.meta.ext.custom_id | url_encode()"
          timeout_ms: 5000
          retry: {max: 2, backoff_ms: 500}

        # 合并：imp 与 event 直接复用 click 模板
        imp: *click_tpl
        event: *click_tpl
      
      # NotNull平台回调处理配置（无验证）
      inbound_callback:
        event:
          source: "query"  # 回调参数来源于URL查询参数
          field_map:
            "udm.event.type": "const:event"                    # 固定为event类型
            "udm.event.name": "query._EVENT_"                  # 事件类型：ACTIVATED/REGISTERED/PAID/RETAINED
            "udm.meta.amount": "query._AMOUNT_"                # 付费金额（仅付费事件）
            "udm.meta.days": "query._DAYS_"                    # 留存天数（仅留存事件）
            "udm.time.ts": "udm.time.ts"                       # 使用当前时间戳

# 不需要兜底配置（采用动态回调模板闭环）
downstreams: []

# 路由配置
routes:
  - match_key: "campaign_id"
    rules:
      # NotNull提供的具体广告活动ID
      - equals: "12345"
        upstream: "notnull_upstream"
        downstream: "media_partner_1"
      
      - equals: "67890"
        upstream: "notnull_upstream"
        downstream: "media_partner_1"
    
    # 兜底路由
    fallback_upstream: "notnull_upstream"
    fallback_downstream: "media_partner_1"
