version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: adrouter-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ad_router
      MYSQL_USER: adrouter
      MYSQL_PASSWORD: adrouter123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 卡普卡应用
  adrouter:
    build: .
    container_name: adrouter-app
    restart: unless-stopped
    ports:
      - "6789:6789"
    environment:
      # MySQL 连接配置
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DB: ad_router
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./config_notnull.yaml:/app/config_notnull.yaml:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6789/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
