id: "adapi"
name: "微风互动"
description: "微风互动广告平台"

# NotNull广告平台上游配置（公共接口，无需验证）
adapters:
  outbound:
    click:
      method: "GET"
      url: "http://ad.adapi.cn/click?aid={{aid}}&did={{did}}&os={{os}}&ts={{ts}}&callback={{callback}}&oaid={{oaid}}&imei={{imei}}&android_id={{android_id}}&idfa={{idfa}}&caid={{caid}}&ip={{ip}}&ua={{ua}}&model={{model}}&x={{x}}"
      macros:
        # 必填参数
        aid: "udm.ad.ad_id | url_encode()"
        did: "const:kpk"
        os: "udm.device.os | to_upper()"
        ts: "udm.time.ts"
        callback: "cb_url() | url_encode()"
        # Android
        oaid: "udm.device.oaid | url_encode()"
        imei: "udm.device.imei | url_encode()"
        android_id: "udm.device.android_id | url_encode()"
        # iOS
        idfa: "udm.device.idfa | url_encode()"
        caid: "udm.device.caid | url_encode()"
        # 可选
        ip: "udm.net.ip | url_encode()"
        ua: "udm.net.ua | normalize_encode()"
        model: "udm.device.model | url_encode()"
        x: "udm.meta.ext.custom_id | url_encode()"
      timeout_ms: 8000
      retry: {max: 0, backoff_ms: 500}

  # NotNull平台回调处理配置（无验证）
  inbound_callback:
    event:
      source: "query"  # 回调参数来源于URL查询参数
      field_map:
        "udm.event.type": "const:event"                    # 固定为event类型
        "udm.event.name": "query.event_type"              # 事件类型：ACTIVATED/REGISTERED/PAID/RETAINED
        "udm.meta.amount": "query.amount"                 # 付费金额（仅付费事件）
        "udm.meta.days": "query.days"                     # 留存天数（仅留存事件）
        "udm.time.ts": "now_ms()"                         # 使用当前时间戳