# OCPX中转系统 - 主配置文件
# 这个文件包含系统基础设置、上游配置引用和路由规则

# 系统基础配置
settings:
  callback_base: "http://ikpk.notnull.cc:6789"
  timezone: "Asia/Shanghai"
  app_secret: "notnull_callback_secret_2024"
#  ingress_aliases:
#    event_type: [ "reporting_type", "etype", "type" ]
#    ad_id: [ "ca_id", "aid", "adid" ]
#    click_id: [ "clickid", "clid", "clickId" ]
#    ua: [ "user_agent", "ua" ]
#    device_os: [ "os" ]
#    device_model: [ "model" ]
#    device_android_id: [ "androidId", "android_id", "androidid" ]
#    device_mac: [ "mac", "device_mac" ]
#    callback: [ "callback_url", "callback" ]

# 上游配置文件列表
upstream_configs:
  - id: "adapi"
    name: "微风互动"
    source: "local"
    path: "upstreams/adapi.yaml"
    required: true
    enabled: true
    
  - id: "duokaiyou"
    name: "多开游"
    source: "local"
    path: "upstreams/duokaiyou.yaml"
    required: true
    enabled: true

# 下游配置文件列表（可选）
downstream_configs: []

# 路由配置 - 决定请求如何路由到不同的上游
routes:
  - match_key: "ad_id"
    rules:
      # 微风互动的广告ID规则
      - equals: "67576"
        upstream: "adapi"
        enabled: true
        throttle: 0.2  # 扣量20%
        
      - equals: "10_60_683572_8"
        upstream: "adapi"
        enabled: true
        throttle: 0.2
        
      # 多开游的广告ID规则
      - equals: "68a58f8ab82a4"
        upstream: "duokaiyou"
        enabled: true
        throttle: 0.2
      
      - equals: "68ae719ed76c8"
        upstream: "duokaiyou"
        enabled: true
        throttle: 0.2
        
    # 兜底配置：当没有匹配到具体规则时使用
    fallback_upstream: ""  # 空字符串表示无兜底
    fallback_enabled: false
    fallback_throttle: 0.2